CREATE TABLE AUTHORIZATION_RULE (
  ID_AUTHORIZATION_RULE INT NOT NULL,
  COD_AUTHORIZATION_RULE INT NOT NULL,
  AGE INT NOT NULL,
  GENDER CHAR NOT NULL,
  ALLOWED VARCHAR(3) NOT NULL,
  constraint PK_AUTHORIZATION_RULE primary key (ID_AUTHORIZATION_RULE)
);

INSERT INTO AUTHORIZATION_RULE (ID_AUTHORIZATION_RULE,COD_AUTHORIZATION_RULE, AGE, GENDER, ALLOWED)
VALUES (1,4567, 20, "M", "YES");
INSERT INTO AUTHORIZATION_RULE (ID_AUTHORIZATION_RULE,COD_AUTHORIZATION_RULE, AGE, GENDER, ALLOWED)
VALUES (2,6789, 10, "M", "YES");
INSERT INTO AUTHORIZATION_RULE (ID_AUTHORIZATION_RULE,COD_AUTHORIZATION_RULE, AGE, GENDER, ALLOWED)
VALUES (3,1234, 20, "M", "YES");
INSERT INTO AUTHORIZATION_RULE (ID_AUTHORIZATION_RULE,COD_AUTHORIZATION_RULE, AGE, GENDER, ALLOWED)
VALUES (4,4567, 30, "F", "YES");