CREATE TABLE MEDICAL_PROCEDURE_REQUEST (
  ID_MEDICAL_PROCEDURE_REQUEST INT NOT NULL,
  COD_MEDICAL_PROCEDURE INT NOT NULL,
  PATIENT_NAME
  PATIENT_AGE INT NOT NULL,
  PATIENT_GENDER CHAR NOT NULL,
  constraint PK_MEDICAL_PROCEDURE_REQUEST primary key (ID_MEDICAL_PROCEDURE_REQUEST)
);