CREATE TABLE AUTHORIZATION_REQUEST (
  ID_AUTHORIZATION_REQUEST INT NOT NULL,
  COD_AUTHORIZATION_RULE INT NOT NULL,
  PATIENT_AGE INT NOT NULL,
  PATIENT_GENDER CHAR NOT NULL,
  constraint PK_AUTHORIZATION_REQUEST primary key (ID_AUTHORIZATION_REQUEST)
);